version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: backend:1
    build: ./backend
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "9229:9229" 
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/backend
      - ./backend/node_modules:/usr/src/backend/node_modules

  frontend:
    image: frontend-1
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      - BACKEND_URL=backend:${BACKEND_PORT}

volumes:
  postgres_data: